services:

    mongodb:
        hostname: mongodb
        container_name: mongodb
        image: mongo:7.0.2
        ports:
            - '27017:27017'
        volumes:
            - mongodb_data:/data/db

volumes:
    mongodb_data:
